# Generated by Django 3.2 on 2023-01-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230119_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
