# Generated by Django 3.2 on 2023-01-30 17:49

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    users.validators.validate_username_max_length,
                    users.validators.validate_username,
                ],
                verbose_name='Имя пользователя',
            ),
        ),
    ]
