# Generated by Django 3.2 on 2023-01-17 21:05

from django.db import migrations, models
import reviews.validator


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230118_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(default=1, validators=[reviews.validator.validate_score], verbose_name='Оценка'),
        ),
    ]
